yolo_model:

  config_file:
    name: iros2021-tiny.cfg
  weight_file:
    name: iros2021-tiny_10000.weights
  threshold:
    value: 0.05
  detection_classes:
    names:
      - ring0
      - ring1
      - ring2
      - ring3
