yolo_model:

  config_file:
    name: iros2021-tiny.cfg
  weight_file:
    name: tuttifruit_best.weights
  threshold:
    value: 0.025
  detection_classes:
    names:
      - lethal
      - danger
      - warning
      - safe
